### ISSUE TITLE
Error - 403. Your client does not have permission to access this page at this time. Contact us on support@futbin.com

### ISSUE THREAD

**Issue by mehmettopal** [Mardaneus86/futwebapp-tampermonkey#248] opened 2020-11-15 12:10 UTC
Error - 403. Your client does not have permission to access this page at this time. Contact us on support@futbin.com

**Comment by Mardaneus86** [comment] 2020-11-15 13:31
Duplicate of #199

**Closed by Mardaneus86** 2020-11-15 13:31 UTC
Labels: enhancement
