### ISSUE TITLE
Buy Now Button displaying part of script?

### ISSUE THREAD

**Issue by captain-nev** [Mardaneus86/futwebapp-tampermonkey#70] opened 2017-10-26 04:33 UTC
Buy Now button showing *infopanel.label.buynowfor instead of listed buy now price, not sure why? Occurring on Windows 10 Chrome

**Comment by captain-nev** [comment] 2017-10-26 05:03
Ignore... It's an EA issue.

**Comment by Mardaneus86** [comment] 2017-10-26 07:56
Alright, closing as it's not caused by the scripts.

**Closed by Mardaneus86** 2017-10-26 07:56 UTC
