### ISSUE TITLE
Update to FIFA 19 Web App

### ISSUE THREAD

**Issue by DeRutterQS** [Mardaneus86/futwebapp-tampermonkey#111] opened 2018-09-18 06:18 UTC
Over the last Month i got used to your great work. 
Cannot imagine a Web App without the Futbin Price next to Player name.

Are you planning to continue the work for Fifa 19?

**Comment by Mardaneus86** [comment] 2018-09-19 23:37
Investigation of the new app made clear that the underlying code of the web app changed quite a bit. The `gNavManger` on which most of the code is based, is no longer a global JS variable, so another hook needs to be found for that first.

I'll add my findings to this issue for reference purposes.

**Comment by Tro11z** [comment] 2018-09-20 06:27
I used the auto-list feature almost all year. Would love to see it return when you have the time for it.

**Comment by DeRutterQS** [comment] 2018-09-20 08:09
Thanks for all that effort you put into this.

**Comment by Feigenstaub** [comment] 2018-09-21 11:49
thanks the the effeort last year, mostly I used:
- futbin price (awesome), 
- the button to find the current lowest bin (awesome 2.0) 
- auto relist (awesome 3.0)
Seriously, that 3 things I would love to see again this year. :)

**Comment by HopkinsC1** [comment] 2018-09-21 23:57
Echoing everyone else's compliments, been really great for 18.

As for me I'd love to see the transfer market refresh button, that was top tier. 

Thanks again!

**Comment by Feigenstaub** [comment] 2018-09-22 11:54
> Echoing everyone else's compliments, been really great for 18.
> 
> As for me I'd love to see the transfer market refresh button, that was top tier.
> 
> Thanks again!

I never figured out how that refresh transferlist feature works. If that would mean it refreshes my current search on the transfermarket where I can stay in the 59th minute, that would be awesome 9000. But it did not for me.

**Comment by Mardaneus86** [comment] 2018-09-22 12:32
Thanks for the compliments all. I'm making progress but it takes some time. Futbin integration is working in my local environment. Working on the link to the exact Futbin page now. ETA for Futbin integration is tomorrow if nothing unexpected happens.

<img width="1222" alt="Futbin integration" src="https://user-images.githubusercontent.com/7780108/45917291-19045c00-be74-11e8-8e59-bb0f06ad527e.png">

I'm going to disable all other functionalities and release part by part as soon as it is working again.

**Comment by guiseppeshen** [comment] 2018-09-22 18:38
Looks great, really loved your work for last year's app and look forward to the futbin and also the price check within the app feature.  both were great.

**Comment by Mardaneus86** [comment] 2018-09-22 21:02
Released the [first version for FIFA 19 with Futbin integration](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/1.0.0). I'm thinking about adding Google Analytics to figure out which features to spend my time on.

By the way, if you like and benefit from this project, you can buy me a beer :beers: 😉 
[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VTXU8XUY8JS94)

Keep in mind to enable the features through the settings page, which you can open by clicking on the bottom right icon (it's not a nice settings icon anymore, that will be fixed in the next version).

**Comment by fut837492** [comment] 2018-09-22 23:08
Hi @Mardaneus86 ,

I'm currently looking through this myself and I'm struggling to find how to add a new nav tab item (plus a view, similar to the autobuyer screen/section you had last year), the proper way, not just injected html/css through js. Do you have an pointers? I've tried adding a few things but none seem to work - not as clear as last year!.

Thanks!

**Comment by Bradders591** [comment] 2018-09-24 08:04
> keep in mind to enable the features through the settings page, which you can open by clicking on the bottom right icon (it's not a nice settings icon anymore, that will be fixed in the next


Am i going mad? I can't see this... Version 1.0.2

**Comment by Mardaneus86** [comment] 2018-09-24 08:08
What is it that you can't see? The settings icon? You have to enable Futbin in the settings first. Please reach out on Gitter if you can't get it solved so we can focus on the update to FIFA 19 process here.

<img width="309" alt="Settings icon" src="https://user-images.githubusercontent.com/7780108/45942165-a2856c80-bfe1-11e8-9130-2e80f883c673.png">

**Comment by Bradders591** [comment] 2018-09-24 08:12
Yeah, can't see the settings. I dropped the old version this morning, installed new one (with 19 support) and restarted browser etc. Not there. I'll have a play around and see if i can figure it out. Will update either way. Thanks for the screenshot!

**Comment by Bluey25** [comment] 2018-09-25 03:16
This combined with the shortfuts chrome extension greatly improved my experience of the web app in 18 so I'm glad to see it back. 

Aside from the futbin integration I mostly used the following:

Refresh transfer list - made sniping players (combined with the keyboard shortcut from shortfuts) far easier and doesn't result in repetitive strain.

Check on current lowest BIN - Great bit of information to have without scrolling through x amount of pages.

Thanks for the great work.

**Comment by guiseppeshen** [comment] 2018-09-25 15:11
Really looking forward to "Check on current lowest BIN" if you can do it Tim

**Comment by Mardaneus86** [comment] 2018-09-25 15:36
"Find Min BIN" seems to be the most requested feature as far as I can tell based on the feedback. It's not a question about if it can be done, but by doing it without looking like a bot, thus imposing a ban risk. This kind of feature will take some effort to do without risking you guys to get banned.

I'll see what I can do but no promises or ETA yet!

**Comment by Kyderman** [comment] 2018-09-25 15:37
The BPM bot for days gone by is what got me banned I believe, I actually managed to get myself unbanned the other day. Find min bin should be ok.

**Comment by Mardaneus86** [comment] 2018-09-27 08:11
The WebApp update by EA has no influence on this script, so we're still good to go! 👍

**Comment by YounesElm** [comment] 2018-09-30 10:47
Hi @Mardaneus86 the code which skip the buy now confirmation pop-up has changed ? Where can I find the old code to try to adapt for FUT 19 ?

Thanks for your work, it's awesome.

**Comment by Feigenstaub** [comment] 2018-09-30 12:09
great work, I need to say: I miss the extended transferlist. Would massively reduce the amout of sites I need to go trough :)

**Comment by Mardaneus86** [comment] 2018-09-30 21:08
@YounesElm the "old" code can be found [in this commit](https://github.com/Mardaneus86/futwebapp-tampermonkey/commit/987c235f6443b2d649fe6db74b9e3973285c104f#diff-347ddbb678d47b47498b048f523f7bc6), but it hasn't been in the version that is configurable. Feel free to add a PR with a settings option for it. The actual core code of that option should still work.

@Feigenstaub that should still work the same as last year. However I still have to test it before adding it to the script. Main code for this is [here](https://github.com/Mardaneus86/futwebapp-tampermonkey/blob/master/app/transferlist/list-size.js).

**Comment by ajpiano** [comment] 2018-10-01 17:02
I've got Instant BIN confirm working as a Setting, I'll send a PR for it this evening.

**Comment by fabiocarballo** [comment] 2018-10-02 15:01
hey! I got the fut enhancer 1.2.0 but I can't see the min bin. Is this a known issue? I tried both on Chrome and Firefox.

**Comment by sergiomarquesmoura** [comment] 2018-10-02 15:05
Anything else needed apart from installing the script (confirmed it's enabled on TamperMonkey dashboard) and refreshing the FUT web app? Version 1.2.0 not working on Chrome 69.0.3497.100

**Comment by Mardaneus86** [comment] 2018-10-02 18:27
Please don't use this issue for troubleshooting. Open a new issue or reach out on Gitter so I can take a closer look.

**Comment by YounesElm** [comment] 2018-10-05 08:08
In the new version, is the relisted expired auctions available ?

I can't see it in the enhancement..

Thanks for your awesome work.

**Comment by Mardaneus86** [comment] 2018-10-05 08:38
No, I've thought about it for a long time and decided not to add any features that could be seen as automation (at least not when you are not around), because it could easily be considered botting. See what happened to Shortfuts for example. Aiding in botting/sniping is not something I'd like to add in this script. So only features that improve the usability of the app, without being an unfair advantage to others, will be added.

I know many people liked the auto-relist feature last year, but I don't want this repository to be taken down either 😄

**Comment by Mardaneus86** [comment] 2018-10-12 22:32
Since all the functionality of last years edition is ported, apart from the features I'm not planning to implement, I'm going to close this issue.

Please create separate issues if you want other features added or find any bugs!

**Closed by Mardaneus86** 2018-10-12 22:32 UTC
Labels: help wanted, investigation
