### ISSUE TITLE
Player ratings not being displayed

### ISSUE THREAD

**Issue by debugger48** [Mardaneus86/futwebapp-tampermonkey#117] opened 2018-10-03 01:46 UTC
### Expected behavior:
I updated to the 1.2.0 version and now the player ratings are not showing up in the card when in a list (club, transferlist or transfer market)
<img width="1414" alt="screen shot 2018-10-02 at 7 43 32 pm" src="https://user-images.githubusercontent.com/32649305/46385907-bf720d80-c67b-11e8-9b2a-337ce2b86e71.png">

### Current behavior:
It should show the player's rating as normal

### Metadata:
- **Script version:** 1.2.0
- **Browser:** Chrome
- **OS:** Mac OS Mojave

**Comment by Mardaneus86** [comment] 2018-10-03 07:54
Confirmed, looks like the addition of the Fitness and Contracts didn't go 100% correct. That overlay pushes the existing one for the rating out of the card view.

Thanks for the clear bug report. Will be fixed soon!

**Closed** 2018-10-03 09:53 UTC
Labels: bug
