### ISSUE TITLE
Mark if the bid price is lower that FUTBIN price

### ISSUE THREAD

**Issue by mehrdadie** [Mardaneus86/futwebapp-tampermonkey#187] opened 2019-09-20 07:57 UTC
Hello,
Thanks again for the script, I wonder that is it possible to mark a column if the BID price is lower than FUTBIN price same as "Mark Bargain" feature.

**Comment by Mardaneus86** [comment] 2019-09-20 07:59
Duplicate of #121.

**Closed by Mardaneus86** 2019-09-20 08:00 UTC
Labels: duplicate, enhancement
