### ISSUE TITLE
Colorize bargain using Bid instead of BIN

### ISSUE THREAD

**Issue by DeRutterQS** [Mardaneus86/futwebapp-tampermonkey#123] opened 2018-10-10 06:04 UTC
The new "colorize bargain" Feature is great but its really hard to find a player bargain nowadays. Only with the 59th minute trick and there is still a low chance to find one.

Would be awesome it would compare Futbin price with the bid price of the player and highlight if the Bid is at least 10% lower than the Futbin Price.

**Comment by Mardaneus86** [comment] 2018-10-10 07:37
Dupe of #121.

**Closed by Mardaneus86** 2018-10-10 07:37 UTC
Labels: duplicate
