### ISSUE TITLE
Auto relist all items on transferlist - show how many times it has been listed and not sold

### ISSUE THREAD

**Issue by Mit010** [Mardaneus86/futwebapp-tampermonkey#143] opened 2018-10-21 18:53 UTC
READ BEFORE YOU ADD AN ISSUE: Do not request autobuyer features, because they are considered as cheating. Issues regarding autobuyers will be closed immediately.

### Expected behavior:
Give a detailed explanation of the expected behavior.

### Current behavior:
Give a detailed explanation of the current behavior.

### Metadata:
- **Script version:**
- **Browser:**
- **OS:**

**Comment by Mardaneus86** [comment] 2018-10-21 21:04
Duplicate of #42 

Automatically relisting is unwanted behavior because it could be considered as 'botting'.

**Closed by Mardaneus86** 2018-10-21 21:04 UTC
Labels: duplicate
