### ISSUE TITLE
Prices not shown on players

### ISSUE THREAD

**Issue by DeRutterQS** [Mardaneus86/futwebapp-tampermonkey#163] opened 2019-03-08 12:54 UTC
### Expected behavior:
Futbin prices should be shown on transferpile and players in club.

### Current behavior:
On transferpile and club the Futbin Price is not shown anymore. But on transfer search results it is working.

### Metadata:
- **Script version:** 1.4.1
- **Browser:** Chrome
- **OS:** iOS

**Comment by Mardaneus86** [comment] 2019-03-08 13:56
Duplicate of #162

**Closed by Mardaneus86** 2019-03-08 13:56 UTC
